version: "3.9"
services:
  tracker:
    build: 
      context: .
      dockerfile: tracker/Dockerfile
    container_name: tracker
    ports:
      - "8080:8080"
    networks:
      - bittorrent-net
    
  peer1:
    build: 
      context: .
      dockerfile: client/Dockerfile
    container_name: peer1
    environment:
      - MY_PEER_IP=peer1
    depends_on:
      - tracker
    ports: 
      - "6881:6881"
    networks:
      - bittorrent-net

  peer2:
    build:  
      context: .
      dockerfile: client/Dockerfile
    container_name: peer2
    environment:
      - MY_PEER_IP=peer2
    depends_on:
      - tracker
    ports: 
      - "6882:6881"
    networks:
      - bittorrent-net

networks:
  bittorrent-net:
    external: true
